// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerIdFk")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int>("TableIdFk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerIdFk");

                    b.HasIndex("TableIdFk");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RestaurantAPI.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2047)
                        .HasColumnType("nvarchar(2047)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2047)
                        .HasColumnType("nvarchar(2047)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic pizza with fresh mozzarella, basil, and tomato sauce.",
                            ImageUrl = "https://example.com/images/1",
                            IsPopular = true,
                            Name = "Margherita Pizza",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Creamy pasta with pancetta, parmesan, and black pepper.",
                            ImageUrl = "https://example.com/images/2",
                            IsPopular = true,
                            Name = "Spaghetti Carbonara",
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh salmon fillet grilled to perfection with lemon butter sauce.",
                            ImageUrl = "https://example.com/images/3",
                            IsPopular = false,
                            Name = "Grilled Salmon",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Romaine lettuce, parmesan, croutons, and Caesar dressing.",
                            ImageUrl = "https://example.com/images/4",
                            IsPopular = true,
                            Name = "Caesar Salad",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Juicy beef patty with cheddar, lettuce, tomato, and house sauce.",
                            ImageUrl = "https://example.com/images/5",
                            IsPopular = true,
                            Name = "Beef Burger",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tender chicken in creamy spiced tomato sauce, served with rice.",
                            ImageUrl = "https://example.com/images/6",
                            IsPopular = true,
                            Name = "Chicken Tikka Masala",
                            Price = 14.75m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Mixed vegetables sautéed in soy-ginger sauce, served with noodles.",
                            ImageUrl = "https://example.com/images/7",
                            IsPopular = false,
                            Name = "Vegetable Stir Fry",
                            Price = 11.25m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Assorted nigiri and maki rolls with fresh fish and wasabi.",
                            ImageUrl = "https://example.com/images/8",
                            IsPopular = true,
                            Name = "Sushi Platter",
                            Price = 21.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Rich beef broth with caramelized onions, topped with melted cheese.",
                            ImageUrl = "https://example.com/images/9",
                            IsPopular = false,
                            Name = "French Onion Soup",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "12oz ribeye cooked to order, served with mashed potatoes and veggies.",
                            ImageUrl = "https://example.com/images/10",
                            IsPopular = true,
                            Name = "Ribeye Steak",
                            Price = 24.50m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Warm chocolate cake with molten center, served with vanilla ice cream.",
                            ImageUrl = "https://example.com/images/11",
                            IsPopular = true,
                            Name = "Chocolate Lava Cake",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone.",
                            ImageUrl = "https://example.com/images/12",
                            IsPopular = false,
                            Name = "Tiramisu",
                            Price = 6.75m
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 6
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 6
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 8
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 8
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 10
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 12
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            PasswordHash = "AQAAAAEAACcQAAAAEBi97q4umw8bVqnM/FsxXHASbTUVVvGzGy6W+Jcjpwg4Vzgh+htLWxuEm7ff0/SyAg==",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            PasswordHash = "AQAAAAEAACcQAAAAEHyBdmeLELoMJNGfFeQ9GavSk8cjHFJDsugEYR8HBnXo7vU7EpJl/MHmkXMJ3/m2sQ==",
                            Role = 1,
                            Username = "alice"
                        },
                        new
                        {
                            Id = 3,
                            Email = "",
                            PasswordHash = "AQAAAAEAACcQAAAAEKzkbclkB1AnzmD1ROyWzSdoo+dWdfwtPSlKWnYmaPkWGr6/wfPiD7yMzJrRChVtlQ==",
                            Role = 1,
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.Booking", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });
#pragma warning restore 612, 618
        }
    }
}
